const API=(window.API_BASE||"http://localhost:5000")+"/api";
let products=[];
async function api(path,opts={}){const r=await fetch(API+path,{headers:{"Content-Type":"application/json",...(opts.headers||{})},...opts});const data=await r.json();if(!r.ok)throw new Error(data.message||"Request failed");return data}
function render(list=products){document.getElementById("products").innerHTML=list.map(p=>`<article class="card"><div class="frame-img">${p.image?`<img src="${p.image}" alt="${p.name}" style="max-width:100%;max-height:100%;border-radius:10px">`:p.icon||"👓"}</div><h3>${p.name}</h3><div class="tags">${p.cat} • ${p.type}</div><div class="price">₹${p.price}</div><div class="tags">Size: ${p.size||"52-18-140"}</div><button onclick="enquire('${String(p.name).replace(/'/g,"\\'")}')">View / Enquire</button></article>`).join("")||"<p>No products found.</p>"}
async function loadProducts(){try{products=await api("/products");render()}catch(e){console.error(e);document.getElementById("products").innerHTML="<p>Unable to load products. Please start the backend.</p>"}}
function filterProducts(){let q=document.getElementById("search").value.toLowerCase(),c=document.getElementById("category").value,t=document.getElementById("type").value;render(products.filter(p=>(p.name.toLowerCase().includes(q)||p.type.toLowerCase().includes(q))&&(c==="all"||p.cat===c)&&(t==="all"||p.type===t)))}
async function enquire(name){try{await api("/enquiries",{method:"POST",body:JSON.stringify({name:"Website visitor",phone:"Not provided",message:`Interested in ${name}`,product:name})})}catch(e){}let s=await api("/settings").catch(()=>({whatsapp:""}));let wa=(s.whatsapp||"").replace(/\D/g,"");if(wa){let msg=encodeURIComponent(`Hello Jagdamba Optical, I am interested in the ${name} frame. Please share availability and details.`);window.open(`https://wa.me/${wa}?text=${msg}`,"_blank")}else alert("WhatsApp number is not configured yet.")}
async function sendWhatsApp(e){e.preventDefault();let n=document.getElementById("name").value,p=document.getElementById("phone").value,m=document.getElementById("message").value;try{await api("/enquiries",{method:"POST",body:JSON.stringify({name:n,phone:p,message:m})});let s=await api("/settings");let wa=(s.whatsapp||"").replace(/\D/g,"");if(wa){let msg=encodeURIComponent(`Hello Jagdamba Optical,\nName: ${n}\nPhone: ${p}\nRequirement: ${m}`);window.open(`https://wa.me/${wa}?text=${msg}`,"_blank")}else alert("Enquiry saved. WhatsApp number is not configured yet.");e.target.reset()}catch(err){alert(err.message)}}
async function loadSettings(){try{let s=await api("/settings");document.querySelector(".contact").innerHTML=document.querySelector(".contact").innerHTML.replace("[Edit your store address here]",s.address||"").replace("[Edit State]",s.state||"Delhi").replace("[Edit Phone Number]",s.phone||"").replace("[Edit Timing]",s.hours||"").replace("[Your Address]",s.address||"").replace("[Your Phone]",s.phone||"");}catch(e){}}
function toggleMenu(){document.getElementById("nav").classList.toggle("show")}
loadProducts();loadSettings();